language: node_js
node_js:
  - 4
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage
  - npm run build
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
