dist: trusty
language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
env:
  global:
    - DISPLAY=":99.0"
    - XVFB_OPTS=":99.0 -ac -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset"
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $XVFB_OPTS"
script:
  - exit 0
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
