// SOCKET
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_END = 'SOCKET_END'
export const SOCKET_LIST_DIR = 'SOCKET_LIST_DIR'
export const SOCKET_SHOW_DUSTBIN = 'SOCKET_SHOW_DUSTBIN'
export const SOCKET_CREATE_FILE = 'SOCKET_CREATE_FILE'
export const SOCKET_RENAME_FILE = 'SOCKET_RENAME_FILE'
export const SOCKET_CREATE_DIR = 'SOCKET_CREATE_DIR'

// VIEW
export const SWITCH_VIEW = 'SWITCH_VIEW'

// PATH
export const ADD_PATH = 'ADD_PATH'
export const SLICE_PATH = 'SLICE_PATH'

// FILES
export const ADD_FILE = 'ADD_FILE'
export const REMOVE_FILE = 'REMOVE_FILE'
export const UPDATE_FILE = 'UPDATE_FILE'
export const REFRESH_FILES = 'REFRESH_FILES'

// Modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
