// VIEW
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const ENABLE_LOADING_ANIMATION = 'ENABLE_LOADING_ANIMATION'
export const DISABLE_LOADING_ANIMATION = 'DISABLE_LOADING_ANIMATION'
export const ENABLE_RESTORING = 'ENABLE_RESTORING'
export const DISABLE_RESTORING = 'DISABLE_RESTORING'

// PATH
export const ADD_PATH = 'ADD_PATH'
export const REMOVE_PATH = 'REMOVE_PATH'

// Modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

// FILES
export const OPEN_FILE_SUCCESS = 'OPEN_FILE_SUCCESS'
export const OPEN_FILE_FAILURE = 'OPEN_FILE_FAILURE'
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS'
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS'
export const LOAD_FILES_FAILURE = 'LOAD_FILES_FAILURE'
export const SELECT_FILE = 'SELECT_FILE'
export const DESELECT_FILE = 'DESELECT_FILE'
export const CUT_FILES = 'CUT_FILES'

// HISTORY
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS'
export const RESTORE_VERSION_SUCCESS = 'RESTORE_VERSION_SUCCESS'

// INVITE USER
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS'
export const INVITE_USER_FAILURE = 'USER_INVITE_FAILURE'

// DEVICE
export const DECLARE_DEVICE_SUCCESS = 'DECLARE_DEVICE_SUCCESS'
export const DECLARE_DEVICE_FAILURE = 'DECLARE_DEVICE_FAILURE'
export const CONFIGURE_DEVICE_CLEAR = 'CONFIGURE_DEVICE_CLEAR'
export const CONFIGURE_DEVICE_SUCCESS = 'CONFIGURE_DEVICE_SUCCESS'
export const CONFIGURE_DEVICE_FAILURE = 'CONFIGURE_DEVICE_FAILURE'
export const DEVICE_ACCEPT_CONFIGURATION_TRY_SUCCESS = 'DEVICE_ACCEPT_CONFIGURATION_TRY_SUCCESS'
export const DEVICE_ACCEPT_CONFIGURATION_TRY_FAILURE = 'DEVICE_ACCEPT_CONFIGURATION_TRY_FAILURE'

// EVENT
export const EVENT_SUBSCRIBE_SUCCESS = 'EVENT_SUBSCRIBE_SUCCESS'
export const EVENT_SUBSCRIBE_FAILURE = 'EVENT_SUBSCRIBE_FAILURE'
export const EVENT_UNSUBSCRIBE_SUCCESS = 'EVENT_UNSUBSCRIBE_SUCCESS'
export const EVENT_UNSUBSCRIBE_FAILURE = 'EVENT_UNSUBSCRIBE_FAILURE'
export const EVENT_LISTEN_SUCCESS = 'EVENT_LISTEN_SUCCESS'
export const EVENT_LISTEN_FAILURE = 'EVENT_LISTEN_FAILURE'

// LOGIN
export const LIST_LOGINS_SUCCESS = 'LIST_LOGINS_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// LOGIN
export const LOGGED_SUCCESS = 'LOGGED_SUCCESS'
export const LOGGED_FAILURE = 'LOGGED_FAILURE'

// LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// MOUNTPOINT
export const MOUNT_FILESYSTEM_SUCCESS = 'MOUNT_FILESYSTEM_SUCCESS'
export const MOUNT_FILESYSTEM_FAILURE = 'MOUNT_FILESYSTEM_FAILURE'
export const UMOUNT_FILESYSTEM_SUCCESS = 'UMOUNT_FILESYSTEM_SUCCESS'
export const UMOUNT_FILESYSTEM_FAILURE = 'UMOUNT_FILESYSTEM_FAILURE'

// SOCKET
export const SOCKET_WRITE = 'SOCKET_WRITE'
export const SOCKET_WRITE_FAILURE = 'SOCKET_WRITE_FAILURE'
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS'
export const SOCKET_END_SUCCESS = 'SOCKET_END_SUCCESS'
