// VIEW
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const ENABLE_LOADING_ANIMATION = 'ENABLE_LOADING_ANIMATION'
export const DISABLE_LOADING_ANIMATION = 'DISABLE_LOADING_ANIMATION'

// PATH
export const ADD_PATH = 'ADD_PATH'
export const REMOVE_PATH = 'REMOVE_PATH'

// Modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

// FILES
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS'
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS'
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS'
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS'
export const LOAD_FILES_FAILURE = 'LOAD_FILES_FAILURE'

// HISTORY
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS'
export const RESTORE_VERSION_SUCCESS = 'RESTORE_VERSION_SUCCESS'

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// LOGIN
export const LOGGED_SUCCESS = 'LOGGED_SUCCESS'
export const LOGGED_FAILURE = 'LOGGED_FAILURE'

// LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// SOCKET
export const SOCKET_WRITE = 'SOCKET_WRITE'
export const SOCKET_WRITE_FAILURE = 'SOCKET_WRITE_FAILURE'
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS'
export const SOCKET_END_SUCCESS = 'SOCKET_END_SUCCESS'
