export const ADD_FILE = 'ADD_FILE'
export const DELETE_FILE = 'DELETE_FILE'
export const MOVE_FILE = 'MOVE_FILE'
export const REFRESH_FILES = 'REFRESH_FILES'
export const RENAME_FILE = 'RENAME_FILE'
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const SOCKET_CONNECT = 'SOCKET_CONNECT'
export const SOCKET_END = 'SOCKET_END'
